#!/usr/bin/env python3

'''/*
** EPITECH PROJECT, 2017
** 103cypher
** File description:
** main
*/'''

import sys
from encrypted import *
from number import *
from decrypted import *

if (sys.argv[3] == "0"):
	encrypted()
if (sys.argv[3] == "1"):
	decrypted()
